/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EventIdRouteImport } from './routes/event.$id'
import { Route as CancelTokenRouteImport } from './routes/cancel.$token'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ApiUploadsFilenameRouteImport } from './routes/api.uploads.$filename'
import { Route as AdminEventsNewRouteImport } from './routes/admin.events.new'
import { Route as AdminEventsIdRegistrantsRouteImport } from './routes/admin.events.$id.registrants'
import { Route as AdminEventsIdEditRouteImport } from './routes/admin.events.$id.edit'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CancelTokenRoute = CancelTokenRouteImport.update({
  id: '/cancel/$token',
  path: '/cancel/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const ApiUploadsFilenameRoute = ApiUploadsFilenameRouteImport.update({
  id: '/api/uploads/$filename',
  path: '/api/uploads/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsNewRoute = AdminEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsIdRegistrantsRoute =
  AdminEventsIdRegistrantsRouteImport.update({
    id: '/events/$id/registrants',
    path: '/events/$id/registrants',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEventsIdEditRoute = AdminEventsIdEditRouteImport.update({
  id: '/events/$id/edit',
  path: '/events/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/cancel/$token': typeof CancelTokenRoute
  '/event/$id': typeof EventIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/api/uploads/$filename': typeof ApiUploadsFilenameRoute
  '/admin/events/$id/edit': typeof AdminEventsIdEditRoute
  '/admin/events/$id/registrants': typeof AdminEventsIdRegistrantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/cancel/$token': typeof CancelTokenRoute
  '/event/$id': typeof EventIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/api/uploads/$filename': typeof ApiUploadsFilenameRoute
  '/admin/events/$id/edit': typeof AdminEventsIdEditRoute
  '/admin/events/$id/registrants': typeof AdminEventsIdRegistrantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/cancel/$token': typeof CancelTokenRoute
  '/event/$id': typeof EventIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/api/uploads/$filename': typeof ApiUploadsFilenameRoute
  '/admin/events/$id/edit': typeof AdminEventsIdEditRoute
  '/admin/events/$id/registrants': typeof AdminEventsIdRegistrantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/cancel/$token'
    | '/event/$id'
    | '/admin/'
    | '/admin/events/new'
    | '/api/uploads/$filename'
    | '/admin/events/$id/edit'
    | '/admin/events/$id/registrants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/cancel/$token'
    | '/event/$id'
    | '/admin'
    | '/admin/events/new'
    | '/api/uploads/$filename'
    | '/admin/events/$id/edit'
    | '/admin/events/$id/registrants'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/login'
    | '/cancel/$token'
    | '/event/$id'
    | '/admin/'
    | '/admin/events/new'
    | '/api/uploads/$filename'
    | '/admin/events/$id/edit'
    | '/admin/events/$id/registrants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CancelTokenRoute: typeof CancelTokenRoute
  EventIdRoute: typeof EventIdRoute
  ApiUploadsFilenameRoute: typeof ApiUploadsFilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/event/$id': {
      id: '/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancel/$token': {
      id: '/cancel/$token'
      path: '/cancel/$token'
      fullPath: '/cancel/$token'
      preLoaderRoute: typeof CancelTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/uploads/$filename': {
      id: '/api/uploads/$filename'
      path: '/api/uploads/$filename'
      fullPath: '/api/uploads/$filename'
      preLoaderRoute: typeof ApiUploadsFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/new': {
      id: '/admin/events/new'
      path: '/events/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AdminEventsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$id/registrants': {
      id: '/admin/events/$id/registrants'
      path: '/events/$id/registrants'
      fullPath: '/admin/events/$id/registrants'
      preLoaderRoute: typeof AdminEventsIdRegistrantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$id/edit': {
      id: '/admin/events/$id/edit'
      path: '/events/$id/edit'
      fullPath: '/admin/events/$id/edit'
      preLoaderRoute: typeof AdminEventsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEventsNewRoute: typeof AdminEventsNewRoute
  AdminEventsIdEditRoute: typeof AdminEventsIdEditRoute
  AdminEventsIdRegistrantsRoute: typeof AdminEventsIdRegistrantsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEventsNewRoute: AdminEventsNewRoute,
  AdminEventsIdEditRoute: AdminEventsIdEditRoute,
  AdminEventsIdRegistrantsRoute: AdminEventsIdRegistrantsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CancelTokenRoute: CancelTokenRoute,
  EventIdRoute: EventIdRoute,
  ApiUploadsFilenameRoute: ApiUploadsFilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
